# Generated by Django 5.1.1 on 2024-11-15 21:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Arrendador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=15)),
                ("empresa", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "experiencia",
                    models.IntegerField(
                        default=0, help_text="Años de experiencia como Arrendador."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Arrendatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=15)),
                (
                    "ingresos_mensuales",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ingresos mensuales del Arrendatario",
                        max_digits=10,
                    ),
                ),
                (
                    "ocupacion",
                    models.CharField(
                        help_text="Ocupación del arrendatario", max_length=100
                    ),
                ),
                (
                    "referencias",
                    models.TextField(
                        blank=True, help_text="Referencias anteriores", null=True
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("m2_construidos", models.DecimalField(decimal_places=2, max_digits=5)),
                ("m2_totales", models.DecimalField(decimal_places=2, max_digits=5)),
                ("estacionamientos", models.IntegerField(default=0)),
                ("habitaciones", models.IntegerField(default=1)),
                ("banos", models.IntegerField(default=1)),
                ("direccion", models.CharField(max_length=200)),
                (
                    "tipo_inmueble",
                    models.CharField(
                        choices=[
                            ("casa", "Casa"),
                            ("departamento", "Departamento"),
                            ("oficina", "Oficina"),
                            ("local_comercial", "Local Comercial"),
                            ("terreno", "Terreno"),
                        ],
                        default="casa",
                        max_length=50,
                    ),
                ),
                (
                    "precio_mensual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "arrendador",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inmuebles",
                        to="gestion_inmuebles.arrendador",
                    ),
                ),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inmuebles",
                        to="gestion_inmuebles.comuna",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="comuna",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comunas",
                to="gestion_inmuebles.region",
            ),
        ),
        migrations.CreateModel(
            name="SolicitudArriendo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                (
                    "comentario",
                    models.TextField(
                        blank=True, help_text="Comentarios adicionales", null=True
                    ),
                ),
                (
                    "arrendatario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="gestion_inmuebles.arrendatario",
                    ),
                ),
                (
                    "inmueble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="gestion_inmuebles.inmueble",
                    ),
                ),
            ],
        ),
    ]
