# Generated by Django 5.1.1 on 2024-11-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inmueble",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                ("m2_construidos", models.DecimalField(decimal_places=2, max_digits=5)),
                ("m2_totales", models.DecimalField(decimal_places=2, max_digits=5)),
                ("estacionamientos", models.IntegerField(default=0)),
                ("habitaciones", models.IntegerField(default=1)),
                ("banos", models.IntegerField(default=1)),
                ("direccion", models.CharField(max_length=200)),
                ("comuna", models.CharField(max_length=100)),
                (
                    "tipo_inmueble",
                    models.CharField(
                        choices=[
                            ("casa", "Casa"),
                            ("departamento", "Departamento"),
                            ("oficina", "Oficina"),
                            ("local_comercial", "Local Comercial"),
                            ("terreno", "Terreno"),
                        ],
                        default="casa",
                        max_length=50,
                    ),
                ),
                (
                    "precio_mensual",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
            ],
        ),
    ]
