# Generated by Django 5.1.1 on 2024-11-14 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_inmuebles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=15)),
                (
                    "tipo_usuario",
                    models.CharField(
                        choices=[
                            ("arrendatario", "Arrendatario"),
                            ("arrendador", "Arrendador"),
                        ],
                        default="arrendatario",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"tipo_usuario": "arrendador"},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_inmuebles.profile",
            ),
        ),
        migrations.CreateModel(
            name="SolicitudArriendo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_solicitud", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                        ],
                        default="pendiente",
                        max_length=10,
                    ),
                ),
                (
                    "arrendatario",
                    models.ForeignKey(
                        limit_choices_to={"tipo_usuario": "arrendatario"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gestion_inmuebles.profile",
                    ),
                ),
                (
                    "inmueble",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitudes",
                        to="gestion_inmuebles.inmueble",
                    ),
                ),
            ],
        ),
    ]
