# Generated by Django 5.1.1 on 2024-11-14 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_inmuebles", "0002_alter_inmueble_descripcion_profile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                limit_choices_to={"tipo_usuario": "arrendador"},
                on_delete=django.db.models.deletion.CASCADE,
                to="gestion_inmuebles.profile",
            ),
        ),
    ]
