# Generated by Django 5.1.1 on 2024-11-14 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gestion_inmuebles", "0003_alter_inmueble_arrendador"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudarriendo",
            name="comentario",
            field=models.TextField(
                blank=True, help_text="Additional comments by the tenant.", null=True
            ),
        ),
        migrations.CreateModel(
            name="Arrendador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=15)),
                ("empresa", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "experiencia",
                    models.IntegerField(
                        default=0, help_text="Years of experience as a property owner."
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="inmueble",
            name="arrendador",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inmuebles",
                to="gestion_inmuebles.arrendador",
            ),
        ),
        migrations.CreateModel(
            name="Arrendatario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("rut", models.CharField(max_length=12, unique=True)),
                ("direccion", models.CharField(max_length=200)),
                ("telefono", models.CharField(max_length=15)),
                (
                    "ingresos_mensuales",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Monthly income of the tenant.",
                        max_digits=10,
                    ),
                ),
                (
                    "ocupacion",
                    models.CharField(
                        help_text="Current occupation of the tenant.", max_length=100
                    ),
                ),
                (
                    "referencias",
                    models.TextField(
                        blank=True,
                        help_text="References from previous landlords.",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="solicitudarriendo",
            name="arrendatario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="solicitudes",
                to="gestion_inmuebles.arrendatario",
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
